### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration:interface'
    summary: Configuration related to a shared property.
    name: IDynamicDataSharedPropertyConfiguration
    fullName: IDynamicDataSharedPropertyConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-property-pane!'
    children:
      - '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration#filters:member'
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration#filters:member'
    summary: Filters for the shared property.
    name: filters
    fullName: filters
    langs:
      - typeScript
    type: property
    syntax:
      content: 'filters?: IDynamicDataSharedPropertyFilters;'
      return:
        type:
          - '@microsoft/sp-property-pane!IDynamicDataSharedPropertyFilters:interface'
references:
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyFilters:interface'
    name: IDynamicDataSharedPropertyFilters
