### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration:interface'
    summary: Configuration related to a shared source.
    name: IDynamicDataSharedSourceConfiguration
    fullName: IDynamicDataSharedSourceConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-property-pane!'
    children:
      - '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration#filters:member'
      - '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration#sourcesLabel:member'
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration#filters:member'
    summary: Filters for the shared source.
    name: filters
    fullName: filters
    langs:
      - typeScript
    type: property
    syntax:
      content: 'filters?: IDynamicDataSharedSourceFilters;'
      return:
        type:
          - '@microsoft/sp-property-pane!IDynamicDataSharedSourceFilters:interface'
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration#sourcesLabel:member'
    summary: |-
      User-friendly, localized label for the sources dropdown.

      default value - 'Connect to source'
    name: sourcesLabel
    fullName: sourcesLabel
    langs:
      - typeScript
    type: property
    syntax:
      content: 'sourcesLabel?: string;'
      return:
        type:
          - string
references:
  - uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceFilters:interface'
    name: IDynamicDataSharedSourceFilters
