### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration:interface'
    summary: Web part configuration settings
    name: IPropertyPaneConfiguration
    fullName: IPropertyPaneConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-property-pane!'
    children:
      - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#currentPage:member'
      - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#debounceProperties:member'
      - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#loadingIndicatorDelayTime:member'
      - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#pages:member'
      - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#showLoadingIndicator:member'
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#currentPage:member'
    summary: Page to be displayed on the PropertyPane.
    name: currentPage
    fullName: currentPage
    langs:
      - typeScript
    type: property
    syntax:
      content: 'currentPage?: number;'
      return:
        type:
          - number
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#debounceProperties:member'
    summary: List of properties to debounce the `onPropertyPaneFieldChanged` event.
    remarks: >-
      If your property pane is reactive, the `onPropertyPaneFieldChanged` event will fire with any change to the web
      part properties. This may lead to jank for some property pane controls or web parts. You can use this
      configuration property to debounce the `onPropertyPaneFieldChanged` event for the properties listed; other
      properties will be unaffected.
    isPreview: true
    name: debounceProperties
    fullName: debounceProperties
    langs:
      - typeScript
    type: property
    syntax:
      content: 'debounceProperties?: IPropertyPaneDebounceProperty[];'
      return:
        type:
          - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#debounceProperties~0:complex'
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#loadingIndicatorDelayTime:member'
    summary: Number of milliseconds to be delayed before the loading indicator is shown on the property pane.
    remarks: The default value is 500.
    name: loadingIndicatorDelayTime
    fullName: loadingIndicatorDelayTime
    langs:
      - typeScript
    type: property
    syntax:
      content: 'loadingIndicatorDelayTime?: number;'
      return:
        type:
          - number
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#pages:member'
    summary: Total number of pages on the PropertyPane.
    name: pages
    fullName: pages
    langs:
      - typeScript
    type: property
    syntax:
      content: 'pages: IPropertyPanePage[];'
      return:
        type:
          - '@microsoft/sp-property-pane!IPropertyPaneConfiguration#pages~0:complex'
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#showLoadingIndicator:member'
    summary: Indicates whether the loading indicator should be displayed on top of the property pane or not.
    remarks: >-
      This feature is intended to be used when the user is waiting on a promise to resolve. If set to true, overlay
      loading indicator appears after 500ms (web part author can override this behavior by using overlayLoadingIndicator
      property).


      The reason why we are not showing it immediately is that our intent is to never show the loading indicator. But in
      real life async requests could take long and it becomes necessary to display a loading indicator to the end user.
    name: showLoadingIndicator
    fullName: showLoadingIndicator
    langs:
      - typeScript
    type: property
    syntax:
      content: 'showLoadingIndicator?: boolean;'
      return:
        type:
          - boolean
references:
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#debounceProperties~0:complex'
    name: 'IPropertyPaneDebounceProperty[]'
    fullName: 'IPropertyPaneDebounceProperty[]'
    spec.typeScript:
      - uid: '@microsoft/sp-property-pane!IPropertyPaneDebounceProperty:interface'
        name: IPropertyPaneDebounceProperty
        fullName: IPropertyPaneDebounceProperty
      - name: '[]'
        fullName: '[]'
  - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration#pages~0:complex'
    name: 'IPropertyPanePage[]'
    fullName: 'IPropertyPanePage[]'
    spec.typeScript:
      - uid: '@microsoft/sp-property-pane!IPropertyPanePage:interface'
        name: IPropertyPanePage
        fullName: IPropertyPanePage
      - name: '[]'
        fullName: '[]'
