### YamlMime:TSType
name: ICardSearchFooterConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardSearchFooterConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardSearchFooterConfiguration
summary: Search box footer component configuration.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardSearchFooterParameters:interface" />&gt;
