### YamlMime:TSType
name: ICardTextInputConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardTextInputConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardTextInputConfiguration
summary: Text input component configuration.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardTextInputParameters:interface" />&gt;
