### YamlMime:TSType
name: ICardTextConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardTextConfiguration
summary: Text component configuration.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardTextParameters:interface" />&gt;
