### YamlMime:TSType
name: ICardBarConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardBarConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardBarConfiguration
summary: Secondary text component configuration.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardBarParameters:interface" />&gt;
