### YamlMime:TSType
name: ICardSearchBoxConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardSearchBoxConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardSearchBoxConfiguration
summary: Search box component configuration.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardSearchBoxParameters:interface" />&gt;
