### YamlMime:TSTypeAlias
name: TextInputCardViewActionsFooterConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!TextInputCardViewActionsFooterConfiguration:type'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: TextInputCardViewActionsFooterConfiguration
summary: The footer configuration for the card view templates with text input in the body.
remarks: ''
isPreview: true
isDeprecated: false
syntax: >-
  export declare type TextInputCardViewActionsFooterConfiguration = ICardButtonConfiguration |
  [ICardButtonConfiguration, ICardButtonConfiguration] | undefined;
