### YamlMime:TSTypeAlias
name: ActionConfiguration
uid: '@microsoft/sp-top-actions!ActionConfiguration:type'
package: '@microsoft/sp-top-actions!'
fullName: ActionConfiguration
summary: ''
remarks: ''
isPreview: true
isDeprecated: false
syntax: export declare type ActionConfiguration = IPropertyPaneField<any>;
