### YamlMime:TSTypeAlias
name: ActionConfiguration
uid: '@microsoft/sp-top-actions!ActionConfiguration:type'
package: '@microsoft/sp-top-actions!'
fullName: ActionConfiguration
summary: Configuration used for a single Top Action command.
remarks: ''
isPreview: true
isDeprecated: false
syntax: |-
  export declare type ActionConfiguration<TProperties = any> = Readonly<IPropertyPaneField<TProperties>> & {
      readonly title?: string;
  };
