### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration:interface'
    summary: 'Represents a set of OData properties for objects that allow forms customizations (e.g. SP.List, SP.ContentType).'
    name: IODataFormsClientSideConfiguration
    fullName: IODataFormsClientSideConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-odata-types!'
    children:
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DislpayFormClientSideDisplayTarget:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DisplayFormClientSideComponentId:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DisplayFormClientSideComponentProperties:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideComponentId:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideComponentProperties:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideDisplayTarget:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideComponentId:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideComponentProperties:member'
      - '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideDisplayTarget:member'
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DislpayFormClientSideDisplayTarget:member'
    summary: 'Display Form display target (new tab, panel)'
    name: DislpayFormClientSideDisplayTarget
    fullName: DislpayFormClientSideDisplayTarget
    langs:
      - typeScript
    type: property
    syntax:
      content: 'DislpayFormClientSideDisplayTarget: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DisplayFormClientSideComponentId:member'
    summary: Display Form Customizer component id
    name: DisplayFormClientSideComponentId
    fullName: DisplayFormClientSideComponentId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'DisplayFormClientSideComponentId: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DisplayFormClientSideComponentProperties:member'
    summary: Display Form Customizer component properties
    name: DisplayFormClientSideComponentProperties
    fullName: DisplayFormClientSideComponentProperties
    langs:
      - typeScript
    type: property
    syntax:
      content: 'DisplayFormClientSideComponentProperties: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideComponentId:member'
    summary: Edit Form Customizer component id
    name: EditFormClientSideComponentId
    fullName: EditFormClientSideComponentId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'EditFormClientSideComponentId: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideComponentProperties:member'
    summary: Edit Form Customizer component properties
    name: EditFormClientSideComponentProperties
    fullName: EditFormClientSideComponentProperties
    langs:
      - typeScript
    type: property
    syntax:
      content: 'EditFormClientSideComponentProperties: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideDisplayTarget:member'
    summary: 'Edit Form display target (new tab, panel)'
    name: EditFormClientSideDisplayTarget
    fullName: EditFormClientSideDisplayTarget
    langs:
      - typeScript
    type: property
    syntax:
      content: 'EditFormClientSideDisplayTarget: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideComponentId:member'
    summary: New Form Customizer component id
    name: NewFormClientSideComponentId
    fullName: NewFormClientSideComponentId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'NewFormClientSideComponentId: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideComponentProperties:member'
    summary: New Form Customizer component properties
    name: NewFormClientSideComponentProperties
    fullName: NewFormClientSideComponentProperties
    langs:
      - typeScript
    type: property
    syntax:
      content: 'NewFormClientSideComponentProperties: string | undefined;'
      return:
        type:
          - string | undefined
  - uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideDisplayTarget:member'
    summary: 'New Form display target (new tab, panel)'
    name: NewFormClientSideDisplayTarget
    fullName: NewFormClientSideDisplayTarget
    langs:
      - typeScript
    type: property
    syntax:
      content: 'NewFormClientSideDisplayTarget: string | undefined;'
      return:
        type:
          - string | undefined
