### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-list-subscription!ICreateSubscriptionSettings:interface'
    summary: >-
      A list subscription requires at least a site ID and list ID. If the list is not contained in the root site of a
      web, you need to pass in the subweb id. If the domain you are accessing is different than the current domain, you
      will need to provide it as well.


      In the simple case (say a teamsite document library) in the current site, you can simply provide the library ID,
      and the current domain, site and web will be used.
    name: ICreateSubscriptionSettings
    fullName: ICreateSubscriptionSettings
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-list-subscription!'
    children:
      - '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#callbacks:member'
      - '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#domain:member'
      - '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#listId:member'
      - '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#siteId:member'
      - '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#webId:member'
  - uid: '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#callbacks:member'
    summary: the list of callbacks
    name: callbacks
    fullName: callbacks
    langs:
      - typeScript
    type: property
    syntax:
      content: 'callbacks: ISubscriptionCallbacks;'
      return:
        type:
          - '@microsoft/sp-list-subscription!ISubscriptionCallbacks:interface'
  - uid: '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#domain:member'
    summary: 'In the case of a multi-geography tenancy, you need to provide the domain that the site collection lives in.'
    name: domain
    fullName: domain
    langs:
      - typeScript
    type: property
    syntax:
      content: 'domain?: string;'
      return:
        type:
          - string
  - uid: '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#listId:member'
    summary: 'The Guid of the Sharepoint List. At this point, it needs to be a document library, and not just a list.'
    name: listId
    fullName: listId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'listId?: Guid;'
      return:
        type:
          - '@microsoft/sp-core-library!Guid:class'
  - uid: '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#siteId:member'
    summary: >-
      The SharePoint Site Id (assuming it is not the current site) If the siteId parameter is not provided, the current
      site will be used.
    name: siteId
    fullName: siteId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'siteId?: Guid;'
      return:
        type:
          - '@microsoft/sp-core-library!Guid:class'
  - uid: '@microsoft/sp-list-subscription!ICreateSubscriptionSettings#webId:member'
    summary: >-
      The SharePoint Web Id (assuming it is not the current web) If the webId parameter is not provided, the current web
      will be used.
    name: webId
    fullName: webId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'webId?: Guid;'
      return:
        type:
          - '@microsoft/sp-core-library!Guid:class'
references:
  - uid: '@microsoft/sp-list-subscription!ISubscriptionCallbacks:interface'
    name: ISubscriptionCallbacks
  - uid: '@microsoft/sp-core-library!Guid:class'
    name: Guid
