### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-application-base!'
    summary: SharePoint Framework support for building and extending client-side applications.
    name: '@microsoft/sp-application-base'
    fullName: '@microsoft/sp-application-base'
    langs:
      - typeScript
    type: package
    children:
      - '@microsoft/sp-application-base!ApplicationAccessor:class'
      - '@microsoft/sp-application-base!ApplicationCustomizerContext:class'
      - '@microsoft/sp-application-base!BaseApplicationCustomizer:class'
      - '@microsoft/sp-application-base!IPlaceholderCreateContentOptions:interface'
      - '@microsoft/sp-application-base!PlaceholderContent:class'
      - '@microsoft/sp-application-base!PlaceholderName:enum'
      - '@microsoft/sp-application-base!PlaceholderProvider:class'
references:
  - uid: '@microsoft/sp-application-base!ApplicationAccessor:class'
    name: ApplicationAccessor
  - uid: '@microsoft/sp-application-base!ApplicationCustomizerContext:class'
    name: ApplicationCustomizerContext
  - uid: '@microsoft/sp-application-base!BaseApplicationCustomizer:class'
    name: BaseApplicationCustomizer
  - uid: '@microsoft/sp-application-base!IPlaceholderCreateContentOptions:interface'
    name: IPlaceholderCreateContentOptions
  - uid: '@microsoft/sp-application-base!PlaceholderContent:class'
    name: PlaceholderContent
  - uid: '@microsoft/sp-application-base!PlaceholderName:enum'
    name: PlaceholderName
  - uid: '@microsoft/sp-application-base!PlaceholderProvider:class'
    name: PlaceholderProvider
