### YamlMime:UniversalReference
items:
  - uid: sp-dialog.IDialogConfiguration
    isPreview: true
    summary: The interface for dialog configuration
    name: IDialogConfiguration
    fullName: sp-dialog.IDialogConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-dialog
    children:
      - sp-dialog.IDialogConfiguration.isBlocking
  - uid: sp-dialog.IDialogConfiguration.isBlocking
    isPreview: true
    summary: Whether the dialog can be closed by clicking outside the dialog (on the overlay).
    name: isBlocking
    fullName: sp-dialog.IDialogConfiguration.isBlocking
    langs:
      - typeScript
    type: property
    syntax:
      content: 'isBlocking?: boolean;'
      return:
        type:
          - boolean
