### YamlMime:UniversalReference
items:
  - uid: sp-dialog.IDialogConfiguration
    summary: |-
      > [!NOTE]
      > _This API is provided as a preview for developers and may change based on feedback_
      > _that we receive. Do not use this API in a production environment._

      The interface for dialog configuration
    name: IDialogConfiguration
    fullName: sp-dialog.IDialogConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-dialog
    children:
      - sp-dialog.IDialogConfiguration.isBlocking
  - uid: sp-dialog.IDialogConfiguration.isBlocking
    summary: |-
      > [!NOTE]
      > _This API is provided as a preview for developers and may change based on feedback_
      > _that we receive. Do not use this API in a production environment._

      Whether the dialog can be closed by clicking outside the dialog (on the overlay).
    name: isBlocking
    fullName: sp-dialog.IDialogConfiguration.isBlocking
    langs:
      - typeScript
    type: property
    syntax:
      content: 'isBlocking?: boolean;'
      return:
        type:
          - boolean
