### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-dialog!IDialogConfiguration:interface'
    summary: The interface for dialog configuration
    name: IDialogConfiguration
    fullName: IDialogConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-dialog!'
    children:
      - '@microsoft/sp-dialog!IDialogConfiguration#isBlocking:member'
  - uid: '@microsoft/sp-dialog!IDialogConfiguration#isBlocking:member'
    summary: Whether the dialog can be closed by clicking outside the dialog (on the overlay).
    name: isBlocking
    fullName: isBlocking
    langs:
      - typeScript
    type: property
    syntax:
      content: 'isBlocking?: boolean;'
      return:
        type:
          - boolean
