### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-module-interfaces!IModuleConfiguration:interface'
    summary: This is the base interface for a script module's definition.
    isPreview: true
    name: IModuleConfiguration
    fullName: IModuleConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-module-interfaces!'
    children:
      - '@microsoft/sp-module-interfaces!IModuleConfiguration#shouldNotPreload:member'
      - '@microsoft/sp-module-interfaces!IModuleConfiguration#type:member'
  - uid: '@microsoft/sp-module-interfaces!IModuleConfiguration#shouldNotPreload:member'
    summary: 'If set to `true`<!-- -->, this module should not be preloaded when loading the component.'
    remarks: >-
      The most common case for setting this property to "true" is when a module is defined in a manifest, but is not
      required for the module referenced in "entryModuleId" to load. Modules may be defined that are loaded
      asynchronously, and these modules do not need to be preloaded. This field implicitly defaults to `false`<!-- -->.


      Usage: Instructs the module loader to not preload this module.
    isPreview: true
    name: shouldNotPreload
    fullName: shouldNotPreload
    langs:
      - typeScript
    type: property
    syntax:
      content: 'shouldNotPreload?: boolean;'
      return:
        type:
          - boolean
  - uid: '@microsoft/sp-module-interfaces!IModuleConfiguration#type:member'
    summary: >-
      The type of the script block. `"component"` modules come from a component, `"path"` and `"localizedPath"` modules
      must be available on the paths provided in the `"internalModuleBaseUrls"` field.
    remarks: >-
      Modules with the `"path"` type use the `IPathModuleConfiguration` interface.


      Modules with the `"component"` type use the `IComponentModuleConfiguration` interface. Modules with the
      "localizedPath" type use the `ILocalizedPathModuleConfiguration` interface.


      Supported values: `"component"`<!-- -->, `"path"`<!-- -->, `"localizedPath"`


      Example: `"localized"`
    isPreview: true
    name: type
    fullName: type
    langs:
      - typeScript
    type: property
    syntax:
      content: 'type: ''component'' | ''path'' | ''localizedPath'';'
      return:
        type:
          - '''component'' | ''path'' | ''localizedPath'''
