### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-module-interfaces!IModuleConfiguration:type'
    isPreview: true
    name: IModuleConfiguration
    fullName: IModuleConfiguration
    langs:
      - typeScript
    type: typealias
    syntax:
      content: >-
        export declare type IModuleConfiguration = IComponentModuleConfiguration | IPathModuleConfiguration |
        ILocalizedPathModuleConfiguration;
      return:
        type:
          - '@microsoft/sp-module-interfaces!IModuleConfiguration~0:complex'
    package: '@microsoft/sp-module-interfaces!'
references:
  - uid: '@microsoft/sp-module-interfaces!IModuleConfiguration~0:complex'
    name: IComponentModuleConfiguration | IPathModuleConfiguration | ILocalizedPathModuleConfiguration
    fullName: IComponentModuleConfiguration | IPathModuleConfiguration | ILocalizedPathModuleConfiguration
    spec.typeScript:
      - uid: '@microsoft/sp-module-interfaces!IComponentModuleConfiguration:interface'
        name: IComponentModuleConfiguration
        fullName: IComponentModuleConfiguration
      - name: ' | '
        fullName: ' | '
      - uid: '@microsoft/sp-module-interfaces!IPathModuleConfiguration:interface'
        name: IPathModuleConfiguration
        fullName: IPathModuleConfiguration
      - name: ' | '
        fullName: ' | '
      - uid: '@microsoft/sp-module-interfaces!ILocalizedPathModuleConfiguration:interface'
        name: ILocalizedPathModuleConfiguration
        fullName: ILocalizedPathModuleConfiguration
