### YamlMime:UniversalReference
items:
  - uid: sp-core-library.EnvironmentType
    summary: |
      An enum that describes which type of enviroment the framework is running in.
    name: EnvironmentType
    fullName: EnvironmentType
    langs:
      - typeScript
    type: enum
    package: sp-core-library
    children:
      - sp-core-library.EnvironmentType.ClassicSharePoint
      - sp-core-library.EnvironmentType.Local
      - sp-core-library.EnvironmentType.SharePoint
      - sp-core-library.EnvironmentType.Test
  - uid: sp-core-library.EnvironmentType.ClassicSharePoint
    summary: |
      Indicates that the framework was loaded from a classic server-rendered SharePoint page
    name: ClassicSharePoint
    fullName: ClassicSharePoint
    langs:
      - typeScript
    type: field
  - uid: sp-core-library.EnvironmentType.Local
    summary: >
      Represents the scenario of the framework hosted on a localhost server, which typically cannot access any
      SharePoint REST APIs. Example: A developer uses gulp serve command to test their changes in their browser of
      choice.
    name: Local
    fullName: Local
    langs:
      - typeScript
    type: field
  - uid: sp-core-library.EnvironmentType.SharePoint
    summary: |
      Indicates that the framework was loaded by a client-rendered SharePoint page
    name: SharePoint
    fullName: SharePoint
    langs:
      - typeScript
    type: field
  - uid: sp-core-library.EnvironmentType.Test
    summary: >
      Represents the scenario of the framework hosted in a unit/integration test. Example: A developer running a unit
      test to verify changes to their web part.
    name: Test
    fullName: Test
    langs:
      - typeScript
    type: field
