### YamlMime:UniversalReference
items:
  - uid: sp-core-library.Environment
    summary: |
      This class contains contextual information about the enviroment that is hosting the framework and its components.
    name: Environment
    fullName: Environment
    langs:
      - typeScript
    type: class
    package: sp-core-library
    children:
      - sp-core-library.Environment.type
  - uid: sp-core-library.Environment.type
    summary: |
      An enum that describes which type of enviroment the framework is running in.
    name: type
    fullName: type
    langs:
      - typeScript
    type: property
