### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-core-library!Environment:class'
    summary: Information about the system environment where the SharePoint Framework is running.
    name: Environment
    fullName: Environment
    langs:
      - typeScript
    type: class
    package: '@microsoft/sp-core-library!'
    children:
      - '@microsoft/sp-core-library!Environment.type:member'
  - uid: '@microsoft/sp-core-library!Environment.type:member'
    summary: Indicates the general type of environment where the SharePoint Framework is running.
    name: type
    fullName: type
    langs:
      - typeScript
    type: property
    syntax:
      content: 'static get type(): EnvironmentType;'
      return:
        type:
          - '@microsoft/sp-core-library!EnvironmentType:enum'
references:
  - uid: '@microsoft/sp-core-library!EnvironmentType:enum'
    name: EnvironmentType
