### YamlMime:UniversalReference
items:
  - uid: sp-webpart-base.IDynamicDataSharedSourceConfiguration
    summary: Configuration related to a shared source.
    deprecated:
      content: >-
        This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it
        from there.
    name: IDynamicDataSharedSourceConfiguration
    fullName: IDynamicDataSharedSourceConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - 'SPPropertyPane.IDynamicDataSharedSourceConfiguration '
    package: sp-webpart-base
