### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration:interface'
    summary: Configuration related to a shared source.
    deprecated:
      content: >-
        This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it
        from there.
    name: IDynamicDataSharedSourceConfiguration
    fullName: IDynamicDataSharedSourceConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - '@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration~0:complex'
    inheritance:
      - type: '@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration~1:complex'
    package: '@microsoft/sp-webpart-base!'
references:
  - uid: '@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration~0:complex'
    name: SPPropertyPane.IDynamicDataSharedSourceConfiguration
    fullName: SPPropertyPane.IDynamicDataSharedSourceConfiguration
    spec.typeScript:
      - name: SPPropertyPane.
        fullName: SPPropertyPane.
      - uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration:interface'
        name: IDynamicDataSharedSourceConfiguration
        fullName: IDynamicDataSharedSourceConfiguration
  - uid: '@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration~1:complex'
    name: SPPropertyPane.IDynamicDataSharedSourceConfiguration
    fullName: SPPropertyPane.IDynamicDataSharedSourceConfiguration
    spec.typeScript:
      - name: SPPropertyPane.
        fullName: SPPropertyPane.
      - uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration:interface'
        name: IDynamicDataSharedSourceConfiguration
        fullName: IDynamicDataSharedSourceConfiguration
