### YamlMime:UniversalReference
items:
  - uid: sp-webpart-base.IDynamicDataSharedPropertyConfiguration
    summary: Configuration related to a shared property.
    name: IDynamicDataSharedPropertyConfiguration
    fullName: sp-webpart-base.IDynamicDataSharedPropertyConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-webpart-base
    children:
      - sp-webpart-base.IDynamicDataSharedPropertyConfiguration.filters
  - uid: sp-webpart-base.IDynamicDataSharedPropertyConfiguration.filters
    summary: Filters for the shared property.
    name: filters
    fullName: sp-webpart-base.IDynamicDataSharedPropertyConfiguration.filters
    langs:
      - typeScript
    type: property
    syntax:
      content: 'filters?: IDynamicDataSharedPropertyFilters;'
      return:
        type:
          - IDynamicDataSharedPropertyFilters
