### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration:interface'
    summary: Configuration related to a shared property.
    deprecated:
      content: >-
        This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it
        from there.
    name: IDynamicDataSharedPropertyConfiguration
    fullName: IDynamicDataSharedPropertyConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration~0:complex'
    inheritance:
      - type: '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration~1:complex'
    package: '@microsoft/sp-webpart-base!'
references:
  - uid: '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration~0:complex'
    name: SPPropertyPane.IDynamicDataSharedPropertyConfiguration
    fullName: SPPropertyPane.IDynamicDataSharedPropertyConfiguration
    spec.typeScript:
      - name: SPPropertyPane.
        fullName: SPPropertyPane.
      - uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration:interface'
        name: IDynamicDataSharedPropertyConfiguration
        fullName: IDynamicDataSharedPropertyConfiguration
  - uid: '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration~1:complex'
    name: SPPropertyPane.IDynamicDataSharedPropertyConfiguration
    fullName: SPPropertyPane.IDynamicDataSharedPropertyConfiguration
    spec.typeScript:
      - name: SPPropertyPane.
        fullName: SPPropertyPane.
      - uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration:interface'
        name: IDynamicDataSharedPropertyConfiguration
        fullName: IDynamicDataSharedPropertyConfiguration
