### YamlMime:TSType
name: IDynamicDataSharedPropertyConfiguration
uid: '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration:interface'
package: '@microsoft/sp-webpart-base!'
fullName: IDynamicDataSharedPropertyConfiguration
summary: Configuration related to a shared property.
remarks: ''
isPreview: false
isDeprecated: true
customDeprecatedMessage: >-
  This is obsolete now. This interface has been moved to
  `@microsoft/sp-property-pane`<!-- -->. Please consume it from there.
type: interface
extends: >-
  <xref
  uid="@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration~0:complex"
  />
