### YamlMime:UniversalReference
items:
  - uid: sp-webpart-base.IDynamicDataSharedSourceConfiguration
    summary: Configuration related to a shared source.
    name: IDynamicDataSharedSourceConfiguration
    fullName: sp-webpart-base.IDynamicDataSharedSourceConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-webpart-base
    children:
      - sp-webpart-base.IDynamicDataSharedSourceConfiguration.filters
      - sp-webpart-base.IDynamicDataSharedSourceConfiguration.sourcesLabel
  - uid: sp-webpart-base.IDynamicDataSharedSourceConfiguration.filters
    summary: Filters for the shared source.
    name: filters
    fullName: sp-webpart-base.IDynamicDataSharedSourceConfiguration.filters
    langs:
      - typeScript
    type: property
    syntax:
      content: 'filters?: IDynamicDataSharedSourceFilters;'
      return:
        type:
          - IDynamicDataSharedSourceFilters
  - uid: sp-webpart-base.IDynamicDataSharedSourceConfiguration.sourcesLabel
    summary: |-
      User-friendly, localized label for the sources dropdown.

      default value - 'Connect to source'
    name: sourcesLabel
    fullName: sp-webpart-base.IDynamicDataSharedSourceConfiguration.sourcesLabel
    langs:
      - typeScript
    type: property
    syntax:
      content: 'sourcesLabel?: string;'
      return:
        type:
          - string
