### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-webpart-base!IPropertyPaneConfiguration:interface'
    summary: Web part configuration settings
    deprecated:
      content: >-
        This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it
        from there.
    name: IPropertyPaneConfiguration
    fullName: IPropertyPaneConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - '@microsoft/sp-webpart-base!IPropertyPaneConfiguration~0:complex'
    inheritance:
      - type: '@microsoft/sp-webpart-base!IPropertyPaneConfiguration~1:complex'
    package: '@microsoft/sp-webpart-base!'
references:
  - uid: '@microsoft/sp-webpart-base!IPropertyPaneConfiguration~0:complex'
    name: SPPropertyPane.IPropertyPaneConfiguration
    fullName: SPPropertyPane.IPropertyPaneConfiguration
    spec.typeScript:
      - name: SPPropertyPane.
        fullName: SPPropertyPane.
      - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration:interface'
        name: IPropertyPaneConfiguration
        fullName: IPropertyPaneConfiguration
  - uid: '@microsoft/sp-webpart-base!IPropertyPaneConfiguration~1:complex'
    name: SPPropertyPane.IPropertyPaneConfiguration
    fullName: SPPropertyPane.IPropertyPaneConfiguration
    spec.typeScript:
      - name: SPPropertyPane.
        fullName: SPPropertyPane.
      - uid: '@microsoft/sp-property-pane!IPropertyPaneConfiguration:interface'
        name: IPropertyPaneConfiguration
        fullName: IPropertyPaneConfiguration
