### YamlMime:UniversalReference
items:
  - uid: sp-webpart-base.IPropertyPaneConfiguration
    summary: Web part configuration settings
    name: IPropertyPaneConfiguration
    fullName: sp-webpart-base.IPropertyPaneConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-webpart-base
    children:
      - sp-webpart-base.IPropertyPaneConfiguration.currentPage
      - sp-webpart-base.IPropertyPaneConfiguration.loadingIndicatorDelayTime
      - sp-webpart-base.IPropertyPaneConfiguration.pages
      - sp-webpart-base.IPropertyPaneConfiguration.showLoadingIndicator
  - uid: sp-webpart-base.IPropertyPaneConfiguration.currentPage
    summary: Page to be displayed on the PropertyPane.
    name: currentPage
    fullName: sp-webpart-base.IPropertyPaneConfiguration.currentPage
    langs:
      - typeScript
    type: property
    syntax:
      content: 'currentPage?: number;'
      return:
        type:
          - number
  - uid: sp-webpart-base.IPropertyPaneConfiguration.loadingIndicatorDelayTime
    summary: |-
      Number of milli seconds to be delayed before the loading indicator is shown on the property pane. 

       default is 500.
    name: loadingIndicatorDelayTime
    fullName: sp-webpart-base.IPropertyPaneConfiguration.loadingIndicatorDelayTime
    langs:
      - typeScript
    type: property
    syntax:
      content: 'loadingIndicatorDelayTime?: number;'
      return:
        type:
          - number
  - uid: sp-webpart-base.IPropertyPaneConfiguration.pages
    summary: Total number of pages on the PropertyPane.
    name: pages
    fullName: sp-webpart-base.IPropertyPaneConfiguration.pages
    langs:
      - typeScript
    type: property
    syntax:
      content: 'pages: IPropertyPanePage[];'
      return:
        type:
          - 'IPropertyPanePage[]'
  - uid: sp-webpart-base.IPropertyPaneConfiguration.showLoadingIndicator
    summary: >-
      Indicates whether the loading indicator should be displayed on top of the property pane or not. This feature is
      intended to be used when the user is waiting on a promise to resolve. If set to true, overlay loading indicator
      appears after 500ms (web part author can override this behavior by using overlayLoadingIndicator property). 

       The reason why we are not showing it immediately is that our intent is to never show the loading indicator. But in real life async requests could take long and it becomes necessary to display a loading indicator to the end user.
    name: showLoadingIndicator
    fullName: sp-webpart-base.IPropertyPaneConfiguration.showLoadingIndicator
    langs:
      - typeScript
    type: property
    syntax:
      content: 'showLoadingIndicator?: boolean;'
      return:
        type:
          - boolean
