### YamlMime:UniversalReference
items:
  - uid: sp-webpart-base.IPropertyPaneConfiguration
    summary: Web part configuration settings
    deprecated:
      content: >-
        This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it
        from there.
    name: IPropertyPaneConfiguration
    fullName: IPropertyPaneConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - 'SPPropertyPane.IPropertyPaneConfiguration '
    package: sp-webpart-base
