### YamlMime:TSType
name: IPropertyPaneConfiguration
uid: '@microsoft/sp-webpart-base!IPropertyPaneConfiguration:interface'
package: '@microsoft/sp-webpart-base!'
fullName: IPropertyPaneConfiguration
summary: Web part configuration settings
remarks: ''
isPreview: false
isDeprecated: true
customDeprecatedMessage: >-
  This is obsolete now. This interface has been moved to
  `@microsoft/sp-property-pane`<!-- -->. Please consume it from there.
type: interface
extends: >-
  SPPropertyPane.<xref
  uid="@microsoft/sp-property-pane!IPropertyPaneConfiguration:interface" />
