### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-lodash-subset!ThrottleSettings:type'
    name: ThrottleSettings
    fullName: ThrottleSettings
    langs:
      - typeScript
    type: typealias
    syntax:
      content: export declare type ThrottleSettings = ThrottleSettings2;
      return:
        type:
          - '@types/lodash!~"\"../index\"".ThrottleSettings:interface'
    package: '@microsoft/sp-lodash-subset!'
references:
  - uid: '@types/lodash!~"\"../index\"".ThrottleSettings:interface'
    name: ThrottleSettings2
