### YamlMime:UniversalReference
items:
  - uid: sp-application-base
    summary: SharePoint Framework support for building and extending client-side applications.
    name: '@microsoft/sp-application-base'
    fullName: sp-application-base
    langs:
      - typeScript
    type: package
    children:
      - sp-application-base.ApplicationAccessor
      - sp-application-base.ApplicationCustomizerContext
      - sp-application-base.BaseApplicationCustomizer
      - sp-application-base.IPlaceholderCreateContentOptions
      - sp-application-base.PlaceholderContent
      - sp-application-base.PlaceholderName
      - sp-application-base.PlaceholderProvider
references:
  - uid: sp-application-base.ApplicationAccessor
    name: ApplicationAccessor
  - uid: sp-application-base.ApplicationCustomizerContext
    name: ApplicationCustomizerContext
  - uid: sp-application-base.BaseApplicationCustomizer
    name: BaseApplicationCustomizer
  - uid: sp-application-base.IPlaceholderCreateContentOptions
    name: IPlaceholderCreateContentOptions
  - uid: sp-application-base.PlaceholderContent
    name: PlaceholderContent
  - uid: sp-application-base.PlaceholderName
    name: PlaceholderName
  - uid: sp-application-base.PlaceholderProvider
    name: PlaceholderProvider
