### YamlMime:UniversalReference
items:
  - uid: sp-application-base.ApplicationCustomizerContext
    summary: This object provides contextual information for BaseApplicationCustomizer.
    name: ApplicationCustomizerContext
    fullName: sp-application-base.ApplicationCustomizerContext
    langs:
      - typeScript
    type: class
    extends:
      - ExtensionContext
    package: sp-application-base
    children:
      - sp-application-base.ApplicationCustomizerContext.application
      - sp-application-base.ApplicationCustomizerContext.placeholderProvider
  - uid: sp-application-base.ApplicationCustomizerContext.application
    summary: The application accessor provides access to metadata and events from the application.
    name: application
    fullName: sp-application-base.ApplicationCustomizerContext.application
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public readonly application: ApplicationAccessor;'
      return:
        type:
          - ApplicationAccessor
  - uid: sp-application-base.ApplicationCustomizerContext.placeholderProvider
    summary: Exposes a collection of content placeholders for use by third parties.
    name: placeholderProvider
    fullName: sp-application-base.ApplicationCustomizerContext.placeholderProvider
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public readonly placeholderProvider: PlaceholderProvider;'
      return:
        type:
          - PlaceholderProvider
