### YamlMime:UniversalReference
items:
  - uid: sp-application-base.ApplicationAccessor
    summary: Provides access to the client-side application that is currently executing.
    remarks: >-
      The client-side application determines the user experience for an entire web page. (It is a client-side component
      with a manifest; however, the SharePoint Framework does not yet enable third parties to create their own
      applications.) Within a web page, exactly one client-side application may be executing at a time. Certain in-place
      navigation transitions may cause the application to be unloaded and replaced a different application. 

       The ApplicationAccessor class enables extensibility components such as extensions and web parts to interact with the currently executing application. It acts as a proxy for the real application object (i.e. BaseApplication subclass), to ensure that extensibility components only rely on interactions that would be portable across all applications.
    isPreview: true
    name: ApplicationAccessor
    fullName: sp-application-base.ApplicationAccessor
    langs:
      - typeScript
    type: class
    package: sp-application-base
    children:
      - sp-application-base.ApplicationAccessor.constructor
      - sp-application-base.ApplicationAccessor.navigatedEvent
  - uid: sp-application-base.ApplicationAccessor.constructor
    summary: 'Constructs a new instance of the [ApplicationAccessor](xref:sp-application-base.ApplicationAccessor) class.'
    remarks: >-
      Third parties should not call this constructor. Instead, use the ApplicationAccessor instance from the component
      context, e.g. [BaseApplicationCustomizer.context](xref:sp-application-base.BaseApplicationCustomizer.context) .
    name: constructor(serviceScope)
    fullName: sp-application-base.ApplicationAccessor.constructor
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(serviceScope: ServiceScope);'
      parameters:
        - id: serviceScope
          description: ''
          type:
            - ServiceScope
  - uid: sp-application-base.ApplicationAccessor.navigatedEvent
    summary: An event that is fired when the application's top-level page context navigates to a new page.
    remarks: 'This event fires after the top-level sp-page-context:PageContext has navigated to a new page.'
    isPreview: true
    name: navigatedEvent
    fullName: sp-application-base.ApplicationAccessor.navigatedEvent
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public readonly navigatedEvent: Event<EventArgs>;'
      return:
        type:
          - Event<EventArgs>
