### YamlMime:UniversalReference
items:
  - uid: sp-application-base.ApplicationCustomizerContext
    summary: 'The component context for [BaseApplicationCustomizer](xref:sp-application-base.BaseApplicationCustomizer)<!-- -->.'
    remarks: >-
      The constructor for this class is marked as internal. Third-party code should not call the constructor directly or
      create subclasses that extend the ApplicationCustomizerContext class.
    name: ApplicationCustomizerContext
    fullName: ApplicationCustomizerContext
    langs:
      - typeScript
    type: class
    extends:
      - ExtensionContext
    package: sp-application-base
    children:
      - sp-application-base.ApplicationCustomizerContext.application
      - sp-application-base.ApplicationCustomizerContext.dispose
      - sp-application-base.ApplicationCustomizerContext.placeholderProvider
  - uid: sp-application-base.ApplicationCustomizerContext.application
    summary: Provides access to the client-side application that is currently running.
    name: application
    fullName: application
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly application: ApplicationAccessor;'
      return:
        type:
          - ApplicationAccessor
  - uid: sp-application-base.ApplicationCustomizerContext.dispose
    name: dispose()
    fullName: dispose
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        dispose(): void;
      return:
        type:
          - void
        description: ''
  - uid: sp-application-base.ApplicationCustomizerContext.placeholderProvider
    summary: Exposes a collection of content placeholders for use by third parties.
    name: placeholderProvider
    fullName: placeholderProvider
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly placeholderProvider: PlaceholderProvider;'
      return:
        type:
          - PlaceholderProvider
