### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-application-base!ApplicationCustomizerContext:class'
    summary: >-
      The component context for
      [BaseApplicationCustomizer](xref:@microsoft/sp-application-base!BaseApplicationCustomizer:class)<!-- -->.
    remarks: >-
      The constructor for this class is marked as internal. Third-party code should not call the constructor directly or
      create subclasses that extend the `ApplicationCustomizerContext` class.
    name: ApplicationCustomizerContext
    fullName: ApplicationCustomizerContext
    langs:
      - typeScript
    type: class
    extends:
      - '@microsoft/sp-extension-base!ExtensionContext:class'
    inheritance:
      - type: '@microsoft/sp-extension-base!ExtensionContext:class'
        inheritance:
          - type: '@microsoft/sp-component-base!BaseComponentContext:class'
    package: '@microsoft/sp-application-base!'
    children:
      - '@microsoft/sp-application-base!ApplicationCustomizerContext#application:member'
      - '@microsoft/sp-application-base!ApplicationCustomizerContext#dispose:member(1)'
      - '@microsoft/sp-application-base!ApplicationCustomizerContext#placeholderProvider:member'
  - uid: '@microsoft/sp-application-base!ApplicationCustomizerContext#application:member'
    summary: Provides access to the client-side application that is currently running.
    name: application
    fullName: application
    langs:
      - typeScript
    type: property
    syntax:
      content: 'get application(): ApplicationAccessor;'
      return:
        type:
          - '@microsoft/sp-application-base!default:class'
  - uid: '@microsoft/sp-application-base!ApplicationCustomizerContext#dispose:member(1)'
    name: dispose()
    fullName: dispose()
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        dispose(): void;
      return:
        type:
          - void
        description: ''
  - uid: '@microsoft/sp-application-base!ApplicationCustomizerContext#placeholderProvider:member'
    summary: Exposes a collection of content placeholders for use by third parties.
    name: placeholderProvider
    fullName: placeholderProvider
    langs:
      - typeScript
    type: property
    syntax:
      content: 'get placeholderProvider(): PlaceholderProvider;'
      return:
        type:
          - '@microsoft/sp-application-base!default:class'
references:
  - uid: '@microsoft/sp-extension-base!ExtensionContext:class'
    name: ExtensionContext
  - uid: '@microsoft/sp-component-base!BaseComponentContext:class'
    name: BaseComponentContext
  - uid: '@microsoft/sp-application-base!default:class'
    name: ApplicationAccessor
