### YamlMime:UniversalReference
items:
  - uid: sp-application-base.ApplicationAccessor
    summary: Provides metadata and events of the SPFx application that's running.
    isPreview: true
    name: ApplicationAccessor
    fullName: sp-application-base.ApplicationAccessor
    langs:
      - typeScript
    type: class
    package: sp-application-base
    children:
      - sp-application-base.ApplicationAccessor.constructor
      - sp-application-base.ApplicationAccessor.navigatedEvent
  - uid: sp-application-base.ApplicationAccessor.constructor
    summary: 'Constructs a new instance of the [ApplicationAccessor](xref:sp-application-base.ApplicationAccessor) class'
    name: constructor(serviceScope)
    fullName: sp-application-base.ApplicationAccessor.constructor
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(serviceScope: ServiceScope);'
      parameters:
        - id: serviceScope
          description: ''
          type:
            - ServiceScope
  - uid: sp-application-base.ApplicationAccessor.navigatedEvent
    summary: Event that gets raised every time there is a page navigation
    isPreview: true
    name: navigatedEvent
    fullName: sp-application-base.ApplicationAccessor.navigatedEvent
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public readonly navigatedEvent: Event<EventArgs>;'
      return:
        type:
          - Event<EventArgs>
