### YamlMime:UniversalReference
items:
  - uid: sp-application-base.ApplicationCustomizerContext
    summary: 'The component context for [BaseApplicationCustomizer](xref:sp-application-base.BaseApplicationCustomizer) .'
    remarks: >-
      The constructor for this class is marked as internal; third party code should not inherit directly from this base
      class.
    name: ApplicationCustomizerContext
    fullName: sp-application-base.ApplicationCustomizerContext
    langs:
      - typeScript
    type: class
    extends:
      - ExtensionContext
    package: sp-application-base
    children:
      - sp-application-base.ApplicationCustomizerContext.application
      - sp-application-base.ApplicationCustomizerContext.placeholderProvider
  - uid: sp-application-base.ApplicationCustomizerContext.application
    summary: Provides access to the client-side application that is currently executing.
    name: application
    fullName: sp-application-base.ApplicationCustomizerContext.application
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public readonly application: ApplicationAccessor;'
      return:
        type:
          - ApplicationAccessor
  - uid: sp-application-base.ApplicationCustomizerContext.placeholderProvider
    summary: Exposes a collection of content placeholders for use by third parties.
    name: placeholderProvider
    fullName: sp-application-base.ApplicationCustomizerContext.placeholderProvider
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public readonly placeholderProvider: PlaceholderProvider;'
      return:
        type:
          - PlaceholderProvider
