### YamlMime:UniversalReference
items:
  - uid: sp-application-base.BaseApplicationCustomizer
    summary: >-
      This is the base class that third parties should extend when implementing a client-side extension that runs when
      an application is first starting.


      In the component manifest, the "extensionType" should be set to "ApplicationCustomizer".
    remarks: >-
      Example usage scenarios for an application customizer might include: rendering custom UI elements inside a
      SharePoint content placeholder, tracking page load statistics, or automatically logging the user out after a
      certain time period.
    name: BaseApplicationCustomizer
    fullName: sp-application-base.BaseApplicationCustomizer
    langs:
      - typeScript
    type: class
    extends:
      - BaseExtension
    package: sp-application-base
    children:
      - sp-application-base.BaseApplicationCustomizer.context
  - uid: sp-application-base.BaseApplicationCustomizer.context
    summary: Use the context object to access common services and state associated with the component.
    remarks: >-
      Child classes are expected to override this field by redeclaring it with a specialized type. It is meant to be a
      read-only property; the type cannot be declared as read-only in the base class (because it is initialized outside
      the constructor), but child classes should redeclare it as readonly.
    name: context
    fullName: sp-application-base.BaseApplicationCustomizer.context
    langs:
      - typeScript
    type: property
    syntax:
      content: 'protected readonly context: ApplicationCustomizerContext;'
      return:
        type:
          - sp-application-base.ApplicationCustomizerContext
