### YamlMime:UniversalReference
items:
  - uid: sp-http.IHttpClientConfiguration
    summary: Flags interface for HttpClientConfiguration.
    name: IHttpClientConfiguration
    fullName: sp-http.IHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-http
