### YamlMime:UniversalReference
items:
  - uid: sp-http.ISPHttpClientConfiguration
    summary: Flags interface for SPHttpClientConfiguration.
    name: ISPHttpClientConfiguration
    fullName: sp-http.ISPHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - ISPHttpClientCommonConfiguration
    package: sp-http
    children:
      - sp-http.ISPHttpClientConfiguration.defaultODataVersion
      - sp-http.ISPHttpClientConfiguration.defaultSameOriginCredentials
      - sp-http.ISPHttpClientConfiguration.requestDigest
  - uid: sp-http.ISPHttpClientConfiguration.defaultODataVersion
    summary: Automatically configure the "OData-Version" header.
    remarks: >-
      When this switch is specified (i.e. not undefined): If the "OData-Version" header was not explicitly added for the
      request, then SPHttpClient will add the header to specify the version indicated by defaultODataVersion.


      NOTE: Without an 'OData-Version' header, the SharePoint server currently defaults to Version 3.0 in most cases.
      The recommended version is 4.0.
    name: defaultODataVersion
    fullName: sp-http.ISPHttpClientConfiguration.defaultODataVersion
    langs:
      - typeScript
    type: property
    syntax:
      content: 'defaultODataVersion?: ODataVersion;'
      return:
        type:
          - ODataVersion
  - uid: sp-http.ISPHttpClientConfiguration.defaultSameOriginCredentials
    summary: Automatically configure the RequestInit.credentials.
    remarks: >-
      When this switch is true:


      If RequestInit.credentials is not explicitly specified for the request, then SPHttpClient will assign it to be
      "same-origin". Without this switch, different web browsers may apply different defaults.


      For more information, see the spec: https://fetch.spec.whatwg.org/\#cors-protocol-and-credentials
    name: defaultSameOriginCredentials
    fullName: sp-http.ISPHttpClientConfiguration.defaultSameOriginCredentials
    langs:
      - typeScript
    type: property
    syntax:
      content: 'defaultSameOriginCredentials?: boolean;'
      return:
        type:
          - boolean
  - uid: sp-http.ISPHttpClientConfiguration.requestDigest
    summary: Automatically provide an "X-RequestDigest" header for authentication.
    remarks: >-
      When this switch is true:


      If the "X-RequestDigest" header was not explicitly added for the request, then SPHttpClient will add it if the
      request is a write operation (i.e. an HTTP method other than "GET", "HEAD", or "OPTIONS"). The request digest is
      managed by the DigestCache service. In the case of a cache miss, an additional network request may be performed.
    name: requestDigest
    fullName: sp-http.ISPHttpClientConfiguration.requestDigest
    langs:
      - typeScript
    type: property
    syntax:
      content: 'requestDigest?: boolean;'
      return:
        type:
          - boolean
