### YamlMime:TSType
name: AadHttpClientConfiguration
uid: '@microsoft/sp-http!AadHttpClientConfiguration:class'
package: '@microsoft/sp-http!'
fullName: AadHttpClientConfiguration
summary: Configuration for HttpClient.
remarks: >-
  The HttpClientConfiguration object provides a set of switches for
  enabling/disabling various features of the HttpClient class. Normally these
  switches are set (e.g. when calling HttpClient.fetch()) by providing one of
  the predefined defaults from HttpClientConfigurations, however switches can
  also be changed via the HttpClientConfiguration.overrideWith() method.
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: '(constructor)(flags, overrideFlags)'
    uid: '@microsoft/sp-http!AadHttpClientConfiguration:constructor(1)'
    package: '@microsoft/sp-http!'
    fullName: '(constructor)(flags, overrideFlags)'
    summary: >-
      Constructs a new instance of HttpClientConfiguration with the specified
      flags. The default values will be used for any flags that are missing or
      undefined. If overrideFlags is specified, it takes precedence over flags.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        constructor(flags: IAadHttpClientConfiguration, overrideFlags?:
        IAadHttpClientConfiguration);
      parameters:
        - id: flags
          description: ''
          type: >-
            <xref uid="@microsoft/sp-http!IAadHttpClientConfiguration:interface"
            />
        - id: overrideFlags
          description: ''
          type: >-
            <xref uid="@microsoft/sp-http!IAadHttpClientConfiguration:interface"
            />
properties:
  - name: flags
    uid: '@microsoft/sp-http!AadHttpClientConfiguration#flags:member'
    package: '@microsoft/sp-http!'
    fullName: flags
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'protected flags: IAadHttpClientConfiguration;'
      return:
        type: >-
          <xref uid="@microsoft/sp-http!IAadHttpClientConfiguration:interface"
          />
methods:
  - name: overrideWith(sourceFlags)
    uid: '@microsoft/sp-http!AadHttpClientConfiguration#overrideWith:member(1)'
    package: '@microsoft/sp-http!'
    fullName: overrideWith(sourceFlags)
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        /** @override */

        overrideWith(sourceFlags: IAadHttpClientConfiguration):
        AadHttpClientConfiguration;
      parameters:
        - id: sourceFlags
          description: ''
          type: >-
            <xref uid="@microsoft/sp-http!IAadHttpClientConfiguration:interface"
            />
      return:
        type: '<xref uid="@microsoft/sp-http!default:class" />'
        description: ''
extends: '<xref uid="@microsoft/sp-http!default:class" />'
