### YamlMime:TSType
name: GraphHttpClientConfiguration
uid: sp-http.GraphHttpClientConfiguration
package: sp-http
fullName: GraphHttpClientConfiguration
summary: >-
  Configuration for [GraphHttpClient](<xref uid="xref:sp-http"
  />.GraphHttpClient)&lt;!-- --&gt;.
remarks: >-
  The GraphHttpClientConfiguration object provides a set of switches for
  enabling/disabling various features of the GraphHttpClient class. Normally
  these switches are set (e.g. when calling GraphHttpClient.fetch()) by
  providing one of the predefined defaults from GraphHttpClientConfigurations,
  however switches can also be changed via the
  GraphHttpClientConfiguration.overrideWith() method.
isPreview: true
isDeprecated: true
customDeprecatedMessage: The GraphHttpClient class has been superceded by the MSGraphClient class.
type: class
constructors:
  - name: 'constructor(flags, overrideFlags)'
    uid: sp-http.GraphHttpClientConfiguration.constructor
    package: sp-http
    fullName: constructor
    summary: >-
      Constructs a new instance of GraphHttpClientCommonConfiguration with the
      specified flags.
    remarks: >-
      The default values will be used for any flags that are missing or
      undefined. If overrideFlags is specified, it takes precedence over flags.
    isPreview: false
    isDeprecated: true
    customDeprecatedMessage: The GraphHttpClient class has been superceded by the MSGraphClient class.
    syntax:
      content: >-
        constructor(flags: IGraphHttpClientConfiguration, overrideFlags?:
        IGraphHttpClientConfiguration);
      parameters:
        - id: flags
          description: ''
          type: IGraphHttpClientConfiguration
        - id: overrideFlags
          description: ''
          type: IGraphHttpClientConfiguration
properties:
  - name: flags
    uid: sp-http.GraphHttpClientConfiguration.flags
    package: sp-http
    fullName: flags
    summary: ''
    remarks: ''
    isPreview: true
    isDeprecated: true
    customDeprecatedMessage: The GraphHttpClient class has been superceded by the MSGraphClient class.
    syntax:
      content: 'protected flags: IGraphHttpClientConfiguration;'
      return:
        type: IGraphHttpClientConfiguration
extends: HttpClientConfiguration
