### YamlMime:UniversalReference
items:
  - uid: sp-http.GraphHttpClientConfiguration
    summary: >
      > [!NOTE]

      > _This API is provided as a preview for developers and may change based on feedback_

      > _that we receive. Do not use this API in a production environment._


      The GraphHttpClientConfiguration object provides a set of switches for enabling/disabling various features of the
      GraphHttpClient class. Normally these switches are set (e.g. when calling GraphHttpClient.fetch()) by providing
      one of the predefined defaults from GraphHttpClientConfigurations, however switches can also be changed via the
      GraphHttpClientConfiguration.overrideWith() method.
    name: GraphHttpClientConfiguration
    fullName: sp-http.GraphHttpClientConfiguration
    langs:
      - typeScript
    type: class
    remarks: |+
      **Extends:** `HttpClientConfiguration`

      **Implements:** `IGraphHttpClientConfiguration`

    package: sp-http
    children:
      - sp-http.GraphHttpClientConfiguration.constructor
      - sp-http.GraphHttpClientConfiguration.flags
  - uid: sp-http.GraphHttpClientConfiguration.constructor
    summary: >
      Constructs a new instance of GraphHttpClientCommonConfiguration with the specified flags. The default values will
      be used for any flags that are missing or undefined. If overrideFlags is specified, it takes precedence over
      flags.
    name: 'constructor(flags, overrideFlags)'
    fullName: sp-http.GraphHttpClientConfiguration.constructor
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(flags: IGraphHttpClientConfiguration, overrideFlags?: IGraphHttpClientConfiguration);'
      parameters:
        - id: flags
          description: ''
          type:
            - IGraphHttpClientConfiguration
        - id: overrideFlags
          description: ''
          type:
            - IGraphHttpClientConfiguration
  - uid: sp-http.GraphHttpClientConfiguration.flags
    summary: |+
      > [!NOTE]
      > _This API is provided as a preview for developers and may change based on feedback_
      > _that we receive. Do not use this API in a production environment._

    name: flags
    fullName: sp-http.GraphHttpClientConfiguration.flags
    langs:
      - typeScript
    type: property
    syntax:
      content: 'flags: IGraphHttpClientConfiguration;'
      return:
        type:
          - IGraphHttpClientConfiguration
