### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!HttpClientConfiguration:class'
    summary: Configuration for HttpClient.
    remarks: >-
      The HttpClientConfiguration object provides a set of switches for enabling/disabling various features of the
      HttpClient class. Normally these switches are set (e.g. when calling HttpClient.fetch()) by providing one of the
      predefined defaults from HttpClientConfigurations, however switches can also be changed via the
      HttpClientConfiguration.overrideWith() method.
    name: HttpClientConfiguration
    fullName: HttpClientConfiguration
    langs:
      - typeScript
    type: class
    implements:
      - '@microsoft/sp-http!IHttpClientConfiguration:interface'
    package: '@microsoft/sp-http!'
    children:
      - '@microsoft/sp-http!HttpClientConfiguration:constructor(1)'
      - '@microsoft/sp-http!HttpClientConfiguration#flags:member'
      - '@microsoft/sp-http!HttpClientConfiguration#initializeFlags:member(1)'
      - '@microsoft/sp-http!HttpClientConfiguration#overrideWith:member(1)'
  - uid: '@microsoft/sp-http!HttpClientConfiguration:constructor(1)'
    summary: >-
      Constructs a new instance of HttpClientConfiguration with the specified flags. The default values will be used for
      any flags that are missing or undefined. If overrideFlags is specified, it takes precedence over flags.
    name: '(constructor)(flags, overrideFlags)'
    fullName: '(constructor)(flags, overrideFlags)'
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(flags: IHttpClientConfiguration, overrideFlags?: IHttpClientConfiguration);'
      parameters:
        - id: flags
          description: ''
          type:
            - '@microsoft/sp-http!IHttpClientConfiguration:interface'
          optional: false
        - id: overrideFlags
          description: ''
          type:
            - '@microsoft/sp-http!IHttpClientConfiguration:interface'
          optional: true
  - uid: '@microsoft/sp-http!HttpClientConfiguration#flags:member'
    name: flags
    fullName: flags
    langs:
      - typeScript
    type: property
    syntax:
      content: 'protected flags: IHttpClientConfiguration;'
      return:
        type:
          - '@microsoft/sp-http!IHttpClientConfiguration:interface'
  - uid: '@microsoft/sp-http!HttpClientConfiguration#initializeFlags:member(1)'
    summary: Child classes should override this method to initialize the flags object.
    name: initializeFlags()
    fullName: initializeFlags()
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @virtual */
        protected initializeFlags(): void;
      return:
        type:
          - void
        description: ''
  - uid: '@microsoft/sp-http!HttpClientConfiguration#overrideWith:member(1)'
    summary: 'Child classes should override this method to construct the child class type, rather than the base class type.'
    name: overrideWith(sourceFlags)
    fullName: overrideWith(sourceFlags)
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @virtual */
        overrideWith(sourceFlags: IHttpClientConfiguration): HttpClientConfiguration;
      return:
        type:
          - '@microsoft/sp-http!default:class'
        description: ''
      parameters:
        - id: sourceFlags
          description: ''
          type:
            - '@microsoft/sp-http!IHttpClientConfiguration:interface'
          optional: false
references:
  - uid: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    name: IHttpClientConfiguration
  - uid: '@microsoft/sp-http!default:class'
    name: HttpClientConfiguration
