### YamlMime:UniversalReference
items:
  - uid: sp-http.IAadTokenProviderConfiguration
    summary: Required strings for constructing an AadTokenProvider.
    name: IAadTokenProviderConfiguration
    fullName: IAadTokenProviderConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-http
    children:
      - sp-http.IAadTokenProviderConfiguration.aadInstanceUrl
      - sp-http.IAadTokenProviderConfiguration.aadTenantId
      - sp-http.IAadTokenProviderConfiguration.aadUserId
      - sp-http.IAadTokenProviderConfiguration.redirectUri
      - sp-http.IAadTokenProviderConfiguration.servicePrincipalId
      - sp-http.IAadTokenProviderConfiguration.userEmail
      - sp-http.IAadTokenProviderConfiguration.userPrincipalName
  - uid: sp-http.IAadTokenProviderConfiguration.aadInstanceUrl
    summary: The sign in page used to authenticate with Azure Active Directory. Trailing slashes are forbidden.
    name: aadInstanceUrl
    fullName: aadInstanceUrl
    langs:
      - typeScript
    type: property
    syntax:
      content: 'aadInstanceUrl: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.aadTenantId
    summary: The Azure Active Directory's tenant id.
    name: aadTenantId
    fullName: aadTenantId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'aadTenantId: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.aadUserId
    summary: >-
      The user's Azure Active Directory id. This will be used to ensure that a valid cached token is for the current
      user.
    name: aadUserId
    fullName: aadUserId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'aadUserId?: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.redirectUri
    summary: >-
      The page used to retrieve tokens from Azure Active Directory. This url must be listed in the developer's
      application redirect uris.
    name: redirectUri
    fullName: redirectUri
    langs:
      - typeScript
    type: property
    syntax:
      content: 'redirectUri: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.servicePrincipalId
    summary: The client ID of the developer's Azure Active Directory application.
    name: servicePrincipalId
    fullName: servicePrincipalId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'servicePrincipalId: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.userEmail
    summary: >-
      The user's email address. This will be used to ensure that the current user's identity is used for fetching auth
      tokens.
    deprecated:
      content: This parameter will be ignored. Use userPrincipalName instead
    name: userEmail
    fullName: userEmail
    langs:
      - typeScript
    type: property
    syntax:
      content: 'userEmail?: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.userPrincipalName
    summary: >-
      The user's principal name. This will be used to ensure that the current user's identity is used for fetching auth
      tokens. This parameter will avoid the "Request is ambiguous: multiple user identities are avaliable for the
      current request" error.
    name: userPrincipalName
    fullName: userPrincipalName
    langs:
      - typeScript
    type: property
    syntax:
      content: 'userPrincipalName?: string;'
      return:
        type:
          - string
