### YamlMime:TSType
name: IAadHttpClientConfiguration
uid: '@microsoft/sp-http!IAadHttpClientConfiguration:interface'
package: '@microsoft/sp-http!'
fullName: IAadHttpClientConfiguration
summary: Flags interface for HttpClientConfiguration.
remarks: ''

isPreview: false
isDeprecated: false
type: interface
extends: '<xref uid="@microsoft/sp-http!IHttpClientConfiguration:interface" />'
