### YamlMime:UniversalReference
items:
  - uid: sp-http.IAadTokenProviderConfiguration
    summary: Required strings for constructing an AadTokenProvider.
    isPreview: true
    name: IAadTokenProviderConfiguration
    fullName: sp-http.IAadTokenProviderConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-http
    children:
      - sp-http.IAadTokenProviderConfiguration.aadInstanceUrl
      - sp-http.IAadTokenProviderConfiguration.aadTenantId
      - sp-http.IAadTokenProviderConfiguration.aadUserId
      - sp-http.IAadTokenProviderConfiguration.redirectUri
      - sp-http.IAadTokenProviderConfiguration.servicePrincipalId
  - uid: sp-http.IAadTokenProviderConfiguration.aadInstanceUrl
    summary: The sign in page used to authenticate with Azure Active Directory. Trailing slashes are forbidden.
    isPreview: true
    name: aadInstanceUrl
    fullName: sp-http.IAadTokenProviderConfiguration.aadInstanceUrl
    langs:
      - typeScript
    type: property
    syntax:
      content: 'aadInstanceUrl: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.aadTenantId
    summary: The Azure Active Directory's tenant id.
    isPreview: true
    name: aadTenantId
    fullName: sp-http.IAadTokenProviderConfiguration.aadTenantId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'aadTenantId: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.aadUserId
    summary: >-
      The user's Azure Active Directory id. This will be used to ensure that a valid cached token is for the current
      user.
    isPreview: true
    name: aadUserId
    fullName: sp-http.IAadTokenProviderConfiguration.aadUserId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'aadUserId?: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.redirectUri
    summary: >-
      The page used to retrieve tokens from Azure Active Directory. This url must be listed in the developer's
      application redirect uris.
    isPreview: true
    name: redirectUri
    fullName: sp-http.IAadTokenProviderConfiguration.redirectUri
    langs:
      - typeScript
    type: property
    syntax:
      content: 'redirectUri: string;'
      return:
        type:
          - string
  - uid: sp-http.IAadTokenProviderConfiguration.servicePrincipalId
    summary: The client ID of the developer's Azure Active Directory application.
    isPreview: true
    name: servicePrincipalId
    fullName: sp-http.IAadTokenProviderConfiguration.servicePrincipalId
    langs:
      - typeScript
    type: property
    syntax:
      content: 'servicePrincipalId: string;'
      return:
        type:
          - string
