### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!IAadHttpClientConfiguration:interface'
    summary: Flags interface for HttpClientConfiguration.
    name: IAadHttpClientConfiguration
    fullName: IAadHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - '@microsoft/sp-http!IHttpClientConfiguration:interface'
    inheritance:
      - type: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    package: '@microsoft/sp-http!'
references:
  - uid: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    name: IHttpClientConfiguration
