### YamlMime:UniversalReference
items:
  - uid: sp-http.IAadHttpClientConfiguration
    summary: Flags interface for HttpClientConfiguration.
    name: IAadHttpClientConfiguration
    fullName: IAadHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - sp-http.IHttpClientConfiguration
    package: sp-http
