### YamlMime:UniversalReference
items:
  - uid: sp-http.IGraphHttpClientConfiguration
    isPreview: true
    summary: Flags interface for GraphHttpClientCommonConfiguration
    name: IGraphHttpClientConfiguration
    fullName: sp-http.IGraphHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    remarks: |+
      **Extends:** `IHttpClientConfiguration`

    package: sp-http
