### YamlMime:UniversalReference
items:
  - uid: sp-http.IGraphHttpClientConfiguration
    summary: |-
      > [!NOTE]
      > _This API is provided as a preview for developers and may change based on feedback_
      > _that we receive. Do not use this API in a production environment._

      Flags interface for GraphHttpClientCommonConfiguration
    name: IGraphHttpClientConfiguration
    fullName: sp-http.IGraphHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    remarks: |+
      **Extends:** `IHttpClientConfiguration`

    package: sp-http
