### YamlMime:UniversalReference
items:
  - uid: sp-http.IGraphHttpClientConfigurations
    summary: Standard configurations for GraphHttpClient.
    remarks: >-
      This interface provides standard predefined GraphHttpClientConfiguration objects for use with the GraphHttpClient
      class. In general, clients should choose the latest available version number, which enables all the switches that
      are recommended for typical scenarios. (If new switches are introduced in the future, a new version number will be
      introduced, which ensures that existing code will continue to function the way it did at the time when it was
      tested.)
    isPreview: true
    name: IGraphHttpClientConfigurations
    fullName: sp-http.IGraphHttpClientConfigurations
    langs:
      - typeScript
    type: interface
    package: sp-http
    children:
      - sp-http.IGraphHttpClientConfigurations.v1
  - uid: sp-http.IGraphHttpClientConfigurations.v1
    summary: >-
      This configuration turns off every feature switch for HttpClient. The fetch() behavior will be essentially
      identical to the WHATWG standard API that is documented here: https://fetch.spec.whatwg.org/
    isPreview: true
    name: v1
    fullName: sp-http.IGraphHttpClientConfigurations.v1
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly v1: GraphHttpClientConfiguration;'
      return:
        type:
          - GraphHttpClientConfiguration
