### YamlMime:UniversalReference
items:
  - uid: sp-http.IGraphHttpClientConfiguration
    summary: Flags interface for GraphHttpClientCommonConfiguration
    deprecated:
      content: The GraphHttpClient class has been superceded by the MSGraphClient class.
    isPreview: true
    name: IGraphHttpClientConfiguration
    fullName: IGraphHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - IHttpClientConfiguration
    package: sp-http
