### YamlMime:UniversalReference
items:
  - uid: sp-http.IGraphHttpClientConfiguration
    summary: Flags interface for GraphHttpClientCommonConfiguration
    isPreview: true
    name: IGraphHttpClientConfiguration
    fullName: sp-http.IGraphHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - IHttpClientConfiguration
    package: sp-http
