### YamlMime:TSType
name: IGraphHttpClientConfiguration
uid: sp-http.IGraphHttpClientConfiguration
package: sp-http
fullName: IGraphHttpClientConfiguration
summary: Flags interface for GraphHttpClientCommonConfiguration
remarks: ''
isPreview: true
isDeprecated: true
customDeprecatedMessage: The GraphHttpClient class has been superceded by the MSGraphClient class.
type: interface
extends: IHttpClientConfiguration
