### YamlMime:UniversalReference
items:
  - uid: sp-http.IGraphHttpClientConfiguration
    summary: |
      > [!NOTE]
      > *This API is provided as a preview for developers and may change based on feedback*
      > *that we receive. Do not use this API in a production environment.*

      Flags interface for GraphHttpClientCommonConfiguration
    name: IGraphHttpClientConfiguration
    fullName: sp-http.IGraphHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    package: sp-http
