### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    summary: Flags interface for HttpClientConfiguration.
    name: IHttpClientConfiguration
    fullName: IHttpClientConfiguration
    langs:
      - typeScript
    type: interface
    package: '@microsoft/sp-http!'
