### YamlMime:UniversalReference
items:
  - uid: sp-http.IHttpClientConfigurations
    summary: >-
      This interface provides standard predefined HttpClientConfiguration objects for use with the HttpClient class. In
      general, clients should choose the latest available version number, which enables all the switches that are
      recommended for typical scenarios. (If new switches are introduced in the future, a new version number will be
      introduced, which ensures that existing code will continue to function the way it did at the time when it was
      tested.)
    name: IHttpClientConfigurations
    fullName: sp-http.IHttpClientConfigurations
    langs:
      - typeScript
    type: interface
    package: sp-http
    children:
      - sp-http.IHttpClientConfigurations.v1
  - uid: sp-http.IHttpClientConfigurations.v1
    summary: >-
      This configuration turns off every feature switch for HttpClient. The fetch() behavior will be essentially
      identical to the WHATWG standard API that is documented here: https://fetch.spec.whatwg.org/
    name: v1
    fullName: sp-http.IHttpClientConfigurations.v1
    langs:
      - typeScript
    type: property
    syntax:
      content: 'v1: HttpClientConfiguration;'
      return:
        type:
          - HttpClientConfiguration
