### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
    summary: Flags interface for SPHttpClientCommonConfiguration
    name: ISPHttpClientCommonConfiguration
    fullName: ISPHttpClientCommonConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - '@microsoft/sp-http!IHttpClientConfiguration:interface'
    inheritance:
      - type: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    package: '@microsoft/sp-http!'
    children:
      - '@microsoft/sp-http!ISPHttpClientCommonConfiguration#jsonRequest:member'
      - '@microsoft/sp-http!ISPHttpClientCommonConfiguration#jsonResponse:member'
  - uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration#jsonRequest:member'
    summary: Automatically configure the "Content-Type" header for a JSON payload.
    remarks: >-
      When this switch is true:


      If the "Content-Type" header was not explicitly added for the request, then SPHttpClient will add it if the
      request is a write operation (i.e. an HTTP method other than "GET", "HEAD", or "OPTIONS").


      For OData 3.0, the value is 'application/json;odata=verbose;charset=utf-8'.


      For OData 4.0, the value is 'application/json;charset=utf-8'.
    name: jsonRequest
    fullName: jsonRequest
    langs:
      - typeScript
    type: property
    syntax:
      content: 'jsonRequest?: boolean;'
      return:
        type:
          - boolean
  - uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration#jsonResponse:member'
    summary: Automatically configure the "Accept" header for a JSON payload.
    remarks: |-
      When this switch is true:

      If the "Accept" header was not explicitly added for the request, then SPHttpClient will add it.

      For OData 3.0, the value is 'application/json'.

      For OData 4.0, the value is 'application/json;odata.metadata=minimal'.
    name: jsonResponse
    fullName: jsonResponse
    langs:
      - typeScript
    type: property
    syntax:
      content: 'jsonResponse?: boolean;'
      return:
        type:
          - boolean
references:
  - uid: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    name: IHttpClientConfiguration
