### YamlMime:UniversalReference
items:
  - uid: sp-http.ISPHttpClientConfigurations
    summary: Standard configurations for SPHttpClient.
    remarks: >-
      This interface provides standard predefined SPHttpClientConfiguration objects for use with the SPHttpClient class.
      In general, clients should choose the latest available version number, which enables all the switches that are
      recommended for typical scenarios. (If new switches are introduced in the future, a new version number will be
      introduced, which ensures that existing code will continue to function the way it did at the time when it was
      tested.)
    name: ISPHttpClientConfigurations
    fullName: sp-http.ISPHttpClientConfigurations
    langs:
      - typeScript
    type: interface
    package: sp-http
    children:
      - sp-http.ISPHttpClientConfigurations.v1
  - uid: sp-http.ISPHttpClientConfigurations.v1
    summary: >-
      Version 1 enables these switches:


      consoleLogging = true; jsonRequest = true; jsonResponse = true; defaultSameOriginCredentials = true;
      defaultODataVersion = ODataVersion.v4; requestDigest = true
    name: v1
    fullName: sp-http.ISPHttpClientConfigurations.v1
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly v1: SPHttpClientConfiguration;'
      return:
        type:
          - sp-http.SPHttpClientConfiguration
