### YamlMime:UniversalReference
items:
  - uid: sp-http.ISPHttpClientBatchConfiguration
    summary: Flags interface for SPHttpClientBatchConfiguration.
    isPreview: true
    name: ISPHttpClientBatchConfiguration
    fullName: ISPHttpClientBatchConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - ISPHttpClientCommonConfiguration
    package: sp-http
