### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
    summary: Flags interface for SPHttpClientBatchConfiguration.
    isPreview: true
    name: ISPHttpClientBatchConfiguration
    fullName: ISPHttpClientBatchConfiguration
    langs:
      - typeScript
    type: interface
    extends:
      - '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
    inheritance:
      - type: '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
        inheritance:
          - type: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    package: '@microsoft/sp-http!'
references:
  - uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
    name: ISPHttpClientCommonConfiguration
  - uid: '@microsoft/sp-http!IHttpClientConfiguration:interface'
    name: IHttpClientConfiguration
