### YamlMime:TSType
name: ISPHttpClientBatchConfiguration
uid: '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
package: '@microsoft/sp-http!'
fullName: ISPHttpClientBatchConfiguration
summary: Flags interface for SPHttpClientBatchConfiguration.
remarks: ''
example: []
isPreview: true
isDeprecated: false
type: interface
extends: '<xref uid="@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface" />'
