### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration:class'
    summary: Common base class for SPHttpClientConfiguration and SPHttpClientBatchConfiguration.
    name: SPHttpClientCommonConfiguration
    fullName: SPHttpClientCommonConfiguration
    langs:
      - typeScript
    type: class
    extends:
      - '@microsoft/sp-http!default:class'
    inheritance:
      - type: '@microsoft/sp-http!default:class'
    implements:
      - '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
    package: '@microsoft/sp-http!'
    children:
      - '@microsoft/sp-http!SPHttpClientCommonConfiguration:constructor(1)'
      - '@microsoft/sp-http!SPHttpClientCommonConfiguration#flags:member'
      - '@microsoft/sp-http!SPHttpClientCommonConfiguration#initializeFlags:member(1)'
      - '@microsoft/sp-http!SPHttpClientCommonConfiguration#jsonRequest:member'
      - '@microsoft/sp-http!SPHttpClientCommonConfiguration#jsonResponse:member'
      - '@microsoft/sp-http!SPHttpClientCommonConfiguration#overrideWith:member(1)'
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration:constructor(1)'
    summary: Constructs a new instance of SPHttpClientCommonConfiguration with the specified flags.
    remarks: >-
      The default values will be used for any flags that are missing or undefined. If overrideFlags is specified, it
      takes precedence over flags.
    name: '(constructor)(flags, overrideFlags)'
    fullName: '(constructor)(flags, overrideFlags)'
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(flags: ISPHttpClientCommonConfiguration, overrideFlags?: ISPHttpClientCommonConfiguration);'
      parameters:
        - id: flags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
        - id: overrideFlags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration#flags:member'
    name: flags
    fullName: flags
    langs:
      - typeScript
    type: property
    syntax:
      content: 'protected flags: ISPHttpClientCommonConfiguration;'
      return:
        type:
          - '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration#initializeFlags:member(1)'
    name: initializeFlags()
    fullName: initializeFlags()
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        protected initializeFlags(): void;
      return:
        type:
          - void
        description: ''
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration#jsonRequest:member'
    summary: Automatically configure the "Content-Type" header for a JSON payload.
    remarks: >-
      When this switch is true:


      If the "Content-Type" header was not explicitly added for the request, then SPHttpClient will add it if the
      request is a write operation (i.e. an HTTP method other than "GET", "HEAD", or "OPTIONS").


      For OData 3.0, the value is 'application/json;odata=verbose;charset=utf-8'.


      For OData 4.0, the value is 'application/json;charset=utf-8'.
    name: jsonRequest
    fullName: jsonRequest
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly jsonRequest: boolean;'
      return:
        type:
          - boolean
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration#jsonResponse:member'
    summary: Automatically configure the "Accept" header for a JSON payload.
    remarks: |-
      When this switch is true:

      If the "Accept" header was not explicitly added for the request, then SPHttpClient will add it.

      For OData 3.0, the value is 'application/json'.

      For OData 4.0, the value is 'application/json;odata.metadata=minimal'.
    name: jsonResponse
    fullName: jsonResponse
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly jsonResponse: boolean;'
      return:
        type:
          - boolean
  - uid: '@microsoft/sp-http!SPHttpClientCommonConfiguration#overrideWith:member(1)'
    name: overrideWith(sourceFlags)
    fullName: overrideWith(sourceFlags)
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        overrideWith(sourceFlags: ISPHttpClientCommonConfiguration): SPHttpClientCommonConfiguration;
      return:
        type:
          - '@microsoft/sp-http!default:class'
        description: ''
      parameters:
        - id: sourceFlags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
references:
  - uid: '@microsoft/sp-http!default:class'
    name: HttpClientConfiguration
  - uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
    name: ISPHttpClientCommonConfiguration
