### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration:class'
    summary: 'Configuration for [SPHttpClient](xref:@microsoft/sp-http!SPHttpClient:class)<!-- -->.'
    remarks: >-
      The SPHttpClientConfiguration object provides a set of switches for enabling/disabling various features of the
      SPHttpClient class. Normally these switches are set (e.g. when calling SPHttpClient.fetch()) by providing one of
      the predefined defaults from SPHttpClientConfigurations, however switches can also be changed via the
      SPHttpClientConfiguration.overrideWith() method.
    name: SPHttpClientConfiguration
    fullName: SPHttpClientConfiguration
    langs:
      - typeScript
    type: class
    extends:
      - '@microsoft/sp-http!default:class'
    inheritance:
      - type: '@microsoft/sp-http!default:class'
    implements:
      - '@microsoft/sp-http!ISPHttpClientConfiguration:interface'
    package: '@microsoft/sp-http!'
    children:
      - '@microsoft/sp-http!SPHttpClientConfiguration:constructor(1)'
      - '@microsoft/sp-http!SPHttpClientConfiguration#defaultODataVersion:member'
      - '@microsoft/sp-http!SPHttpClientConfiguration#defaultSameOriginCredentials:member'
      - '@microsoft/sp-http!SPHttpClientConfiguration#flags:member'
      - '@microsoft/sp-http!SPHttpClientConfiguration#initializeFlags:member(1)'
      - '@microsoft/sp-http!SPHttpClientConfiguration#overrideWith:member(1)'
      - '@microsoft/sp-http!SPHttpClientConfiguration#requestDigest:member'
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration:constructor(1)'
    summary: >-
      Constructs a new instance of SPHttpClientConfiguration with the specified flags. The default values will be used
      for any flags that are missing or undefined. If overrideFlags is specified, it takes precedence over flags.
    name: '(constructor)(flags, overrideFlags)'
    fullName: '(constructor)(flags, overrideFlags)'
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(flags: ISPHttpClientConfiguration, overrideFlags?: ISPHttpClientConfiguration);'
      parameters:
        - id: flags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientConfiguration:interface'
        - id: overrideFlags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientConfiguration:interface'
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration#defaultODataVersion:member'
    summary: Automatically configure the "OData-Version" header.
    remarks: >-
      When this switch is specified (i.e. not undefined): If the "OData-Version" header was not explicitly added for the
      request, then SPHttpClient will add the header to specify the version indicated by defaultODataVersion.


      NOTE: Without an 'OData-Version' header, the SharePoint server currently defaults to Version 3.0 in most cases.
      The recommended version is 4.0.
    name: defaultODataVersion
    fullName: defaultODataVersion
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly defaultODataVersion: ODataVersion;'
      return:
        type:
          - '@microsoft/sp-http!default:class'
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration#defaultSameOriginCredentials:member'
    summary: Automatically configure the RequestInit.credentials.
    remarks: >-
      When this switch is true:


      If RequestInit.credentials is not explicitly specified for the request, then SPHttpClient will assign it to be
      "same-origin". Without this switch, different web browsers may apply different defaults.


      For more information, see the spec: https://fetch.spec.whatwg.org/\#cors-protocol-and-credentials
    name: defaultSameOriginCredentials
    fullName: defaultSameOriginCredentials
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly defaultSameOriginCredentials: boolean;'
      return:
        type:
          - boolean
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration#flags:member'
    name: flags
    fullName: flags
    langs:
      - typeScript
    type: property
    syntax:
      content: 'protected flags: ISPHttpClientConfiguration;'
      return:
        type:
          - '@microsoft/sp-http!ISPHttpClientConfiguration:interface'
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration#initializeFlags:member(1)'
    name: initializeFlags()
    fullName: initializeFlags()
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        protected initializeFlags(): void;
      return:
        type:
          - void
        description: ''
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration#overrideWith:member(1)'
    name: overrideWith(sourceFlags)
    fullName: overrideWith(sourceFlags)
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        overrideWith(sourceFlags: ISPHttpClientConfiguration): SPHttpClientConfiguration;
      return:
        type:
          - '@microsoft/sp-http!default:class'
        description: ''
      parameters:
        - id: sourceFlags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientConfiguration:interface'
  - uid: '@microsoft/sp-http!SPHttpClientConfiguration#requestDigest:member'
    summary: Automatically provide an "X-RequestDigest" header for authentication.
    remarks: >-
      When this switch is true:


      If the "X-RequestDigest" header was not explicitly added for the request, then SPHttpClient will add it if the
      request is a write operation (i.e. an HTTP method other than "GET", "HEAD", or "OPTIONS"). The request digest is
      managed by the DigestCache service. In the case of a cache miss, an additional network request may be performed.
    name: requestDigest
    fullName: requestDigest
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly requestDigest: boolean;'
      return:
        type:
          - boolean
references:
  - uid: '@microsoft/sp-http!default:class'
    name: SPHttpClientCommonConfiguration
  - uid: '@microsoft/sp-http!ISPHttpClientConfiguration:interface'
    name: ISPHttpClientConfiguration
