### YamlMime:UniversalReference
items:
  - uid: '@microsoft/sp-http!SPHttpClientBatchConfiguration:class'
    summary: Configuration for SPHttpClientBatch.
    remarks: >-
      The SPHttpClientBatchConfiguration object provides a set of switches for enabling/disabling various features of
      the SPHttpClientBatch class. Normally these switches are set (e.g. when calling SPHttpClientBatch.fetch()) by
      providing one of the predefined defaults from SPHttpClientBatchConfigurations, however switches can also be
      changed via the SPHttpClientBatchConfiguration.overrideWith() method.
    isPreview: true
    name: SPHttpClientBatchConfiguration
    fullName: SPHttpClientBatchConfiguration
    langs:
      - typeScript
    type: class
    extends:
      - '@microsoft/sp-http!default:class'
    inheritance:
      - type: '@microsoft/sp-http!default:class'
    implements:
      - '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
    package: '@microsoft/sp-http!'
    children:
      - '@microsoft/sp-http!SPHttpClientBatchConfiguration:constructor(1)'
      - '@microsoft/sp-http!SPHttpClientBatchConfiguration#flags:member'
      - '@microsoft/sp-http!SPHttpClientBatchConfiguration#initializeFlags:member(1)'
      - '@microsoft/sp-http!SPHttpClientBatchConfiguration#overrideWith:member(1)'
  - uid: '@microsoft/sp-http!SPHttpClientBatchConfiguration:constructor(1)'
    summary: >-
      Constructs a new instance of SPHttpClientBatchConfiguration with the specified flags. The default values will be
      used for any flags that are missing or undefined. If overrideFlags is specified, it takes precedence over flags.
    isPreview: true
    name: '(constructor)(flags, overrideFlags)'
    fullName: '(constructor)(flags, overrideFlags)'
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(flags: ISPHttpClientBatchConfiguration, overrideFlags?: ISPHttpClientBatchConfiguration);'
      parameters:
        - id: flags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
          optional: false
        - id: overrideFlags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
          optional: true
  - uid: '@microsoft/sp-http!SPHttpClientBatchConfiguration#flags:member'
    isPreview: true
    name: flags
    fullName: flags
    langs:
      - typeScript
    type: property
    syntax:
      content: 'protected flags: ISPHttpClientBatchConfiguration;'
      return:
        type:
          - '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
  - uid: '@microsoft/sp-http!SPHttpClientBatchConfiguration#initializeFlags:member(1)'
    isPreview: true
    name: initializeFlags()
    fullName: initializeFlags()
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        protected initializeFlags(): void;
      return:
        type:
          - void
        description: ''
  - uid: '@microsoft/sp-http!SPHttpClientBatchConfiguration#overrideWith:member(1)'
    isPreview: true
    name: overrideWith(sourceFlags)
    fullName: overrideWith(sourceFlags)
    langs:
      - typeScript
    type: method
    syntax:
      content: |-
        /** @override */
        overrideWith(sourceFlags: ISPHttpClientBatchConfiguration): SPHttpClientBatchConfiguration;
      return:
        type:
          - '@microsoft/sp-http!default:class'
        description: ''
      parameters:
        - id: sourceFlags
          description: ''
          type:
            - '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
          optional: false
references:
  - uid: '@microsoft/sp-http!default:class'
    name: SPHttpClientCommonConfiguration
  - uid: '@microsoft/sp-http!ISPHttpClientBatchConfiguration:interface'
    name: ISPHttpClientBatchConfiguration
